// ─── Moa delegate: what an agent spawn carries while the delegate is on ──────
//
// "Moa as the owner's delegate" takes decisions out of TUI typing. Two spawn
// changes follow from it, and both exist ONLY while the delegate is on:
//
//   - A fan-out worker cannot open AskUserQuestion. Its dialog draws in a
//     terminal nobody is watching, and the plugin's PreToolUse hook turns it
//     into an approval record that wakes the HQ brain by typing into its pty.
//     The tool stays LISTED: the spawn's own PreToolUse hook refuses it and
//     tells the worker to call `moa_ask` instead. The worker's settings also
//     set WMUX_MOA_DELEGATE_WORKER, which the plugin's bridge reads to skip
//     its own AskUserQuestion report for a call this hook refuses.
//   - Neither a fan-out worker nor an orchestrator brain may merge a PR through
//     `gh`: a merge goes through the merge lane (moaMergeLane.ts), whose
//     predicates read fresh facts.
//   - `moa_ask` and `moa_ask_status` are allowed outright, so an auto-mode
//     permission classifier never refuses a worker's merge request to Moa.
//
// Both ride the spawn's OWN `--settings` file, never the owner's user settings.
//
// The gate is the existing one, not a new switch: `moa-ask.json` says
// `enabled: true` (shared/moaAskSwitch.ts) AND MoaConfig.askMode is not 'off'.
// With either one off this module writes no file and leaves every command
// exactly as it was.
//
// Measured on claude 2.1.292 (interactive TUI, a local fake Messages API):
//   - `permissions.deny: ["AskUserQuestion"]` drops the tool from the model's
//     tool list, so the call is never made and no PreToolUse hook ever sees
//     it: the worker then asks in plain text and the redirect never reaches
//     it. That rule is therefore only the fallback for a profile whose deny
//     script could not be written (a refused tool beats an unwatched dialog).
//   - `Bash(gh pr merge*)` and `Bash(gh api*merge*)` hold under
//     --dangerously-skip-permissions, including a compound line
//     (`cd x && gh pr merge 3`); `gh pr view` and a plain `gh api` read pass.

import fs from 'node:fs';
import path from 'node:path';
import { getWmuxDir } from '../../daemon/config';
import { tokenize, launcherStem } from '../../shared/agentResume';
import { MOA_ASK_SWITCH_FILENAME, readMoaAskEnabled } from '../../shared/moaAskSwitch';
import { MOA_ASK_STATUS_TOOL, MOA_ASK_TOOL } from '../../shared/moaAsk';
import { splitModelEnvMarker } from '../../shared/workerLaunch';
import { getMoaConfig } from '../deck/deckHqStore';

/** The deny rules that send a merge through the lane instead of `gh`. */
export const MOA_DELEGATE_MERGE_DENY: readonly string[] = ['Bash(gh pr merge*)', 'Bash(gh api*merge*)'];

/** Whether the delegate is on for the instance whose data dir is `dir`.
 *  Fail-closed: anything unreadable reads as off. */
export function isMoaDelegateOn(dir: string = getWmuxDir()): boolean {
  if (!readMoaAskEnabled(path.join(dir, MOA_ASK_SWITCH_FILENAME))) return false;
  try {
    return (getMoaConfig(dir).askMode ?? 'off') !== 'off';
  } catch {
    return false;
  }
}

/** What a worker that reached for AskUserQuestion is told instead. The deny
 *  script writes it to stderr: exit 2 alone says a call failed, not what to do. */
export const WORKER_ASK_DENY_REASON =
  'AskUserQuestion is turned off in this pane: its dialog draws in a terminal nobody is watching. ' +
  `Ask Moa instead: call mcp__wmux__${MOA_ASK_TOOL} with your question and 2-6 options, then poll ` +
  `mcp__wmux__${MOA_ASK_STATUS_TOOL} with the ticketId until it is no longer pending. If it comes back ` +
  'escalated, the owner answers it on Moa\'s card: end your turn without restating the question. ' +
  'The answer arrives in this pane as a new message.';

/** The env var the worker's settings set; the plugin's bridge reads it. */
export const MOA_DELEGATE_WORKER_ENV = 'WMUX_MOA_DELEGATE_WORKER';

/** Tools the worker may call without a permission check. */
export const MOA_DELEGATE_WORKER_ALLOW: readonly string[] = [`mcp__wmux__${MOA_ASK_TOOL}`, `mcp__wmux__${MOA_ASK_STATUS_TOOL}`];

/** The worker's PreToolUse deny script, invoked as `node <script>`. */
export function buildWorkerDenyScript(): string {
  return [
    '// Generated by wmux (delegateSpawnPolicy). Rewritten while the Moa delegate',
    '// is on; edits here are lost.',
    `process.stderr.write(${JSON.stringify(WORKER_ASK_DENY_REASON)} + "\\n");`,
    'process.exit(2);',
    '',
  ].join('\n');
}

/** The worker's `--settings` document. `denyScriptPath` null cannot refuse
 *  AskUserQuestion in a hook, so it falls back to the deny rule. */
export function buildWorkerDelegateSettings(opts: { denyScriptPath: string | null }): Record<string, unknown> {
  const deny = opts.denyScriptPath ? [...MOA_DELEGATE_MERGE_DENY] : ['AskUserQuestion', ...MOA_DELEGATE_MERGE_DENY];
  const settings: Record<string, unknown> = {
    permissions: { allow: [...MOA_DELEGATE_WORKER_ALLOW], deny },
  };
  if (opts.denyScriptPath) {
    settings.env = { [MOA_DELEGATE_WORKER_ENV]: '1' };
    settings.hooks = {
      PreToolUse: [
        {
          matcher: 'AskUserQuestion',
          // `node` on PATH, the same assumption the wmux Claude plugin's own
          // hooks make in a worker pane.
          hooks: [{ type: 'command', command: `node "${opts.denyScriptPath}"` }],
        },
      ],
    };
  }
  return settings;
}

/**
 * A path that reads back byte-identical from inside double quotes on a POSIX,
 * PowerShell or cmd line: no quotes, no `$`/backtick (POSIX and PowerShell
 * expand them), no `%`/`!` (cmd expands them), and no run of backslashes
 * (POSIX collapses `\\` to `\`). Anything else could make the file written
 * and the path passed to --settings differ.
 */
export function isQuotable(p: string): boolean {
  return !/['"`$%!]/.test(p) && !/\\\\/.test(p);
}

/** Write `content` unless the file already holds it. */
function writeIfChanged(file: string, content: string): void {
  try {
    if (fs.readFileSync(file, 'utf8') === content) return;
  } catch {
    /* missing: write it */
  }
  fs.writeFileSync(file, content, { encoding: 'utf8', mode: 0o600 });
}

/**
 * Write the worker profile under `<dir>/delegate/` and return the settings
 * path, or null when it could not be written. The content is fixed, so one
 * pair of files serves every worker; they are rewritten only when they drift.
 */
export function writeWorkerDelegateProfile(dir: string): string | null {
  const root = path.join(dir, 'delegate');
  const settingsPath = path.join(root, 'worker-settings.json');
  if (!isQuotable(settingsPath)) {
    console.warn(`[moa-delegate] the worker settings path cannot be quoted safely; workers launch unchanged: ${settingsPath}`);
    return null;
  }
  try {
    fs.mkdirSync(root, { recursive: true, mode: 0o700 });
  } catch (err) {
    console.warn(`[moa-delegate] could not create ${root}: ${String(err)}`);
    return null;
  }
  let denyScriptPath: string | null = path.join(root, 'worker-deny-ask.js');
  try {
    writeIfChanged(denyScriptPath, buildWorkerDenyScript());
  } catch (err) {
    // Without the hook the settings fall back to the deny rule.
    console.warn(`[moa-delegate] could not write the worker deny script: ${String(err)}`);
    denyScriptPath = null;
  }
  try {
    writeIfChanged(settingsPath, `${JSON.stringify(buildWorkerDelegateSettings({ denyScriptPath }), null, 2)}\n`);
  } catch (err) {
    console.warn(`[moa-delegate] could not write the worker settings: ${String(err)}`);
    return null;
  }
  return settingsPath;
}

/**
 * Splice `--settings="<path>"` right after a `claude` launcher. Any other
 * launcher, a line that already passes `--settings`, and a path that cannot be
 * quoted leave the command unchanged. A leading model-env marker is kept.
 */
export function spliceSettingsFlag(fullCommand: string, settingsPath: string): string {
  const { marker, command } = splitModelEnvMarker(fullCommand);
  if (marker) return marker + spliceSettingsFlag(command, settingsPath);
  if (!isQuotable(settingsPath)) {
    console.warn(`[moa-delegate] the settings path cannot be quoted safely; the launch is left unchanged: ${settingsPath}`);
    return command;
  }
  const tokens = tokenize(command);
  if (tokens.length === 0 || launcherStem(tokens[0].value) !== 'claude') return command;
  if (tokens.slice(1).some((t) => !t.quoted && /^--settings(=|$)/.test(t.value))) return command;
  // The `=` form, like --mcp-config in toolSurfaceLaunch: one word on both shells.
  const at = tokens[0].end;
  return `${command.slice(0, at)} --settings="${settingsPath}"${command.slice(at)}`;
}

export interface DelegateSpawnDeps {
  /** The instance data dir (default: getWmuxDir()). */
  dir?: string;
  isOn?: (dir: string) => boolean;
  writeProfile?: (dir: string) => string | null;
}

/**
 * pty:create's stage for a fan-out worker pane. Returns `options` itself
 * (same reference, nothing read beyond the switch, nothing written) for every
 * create that is not a fan-out task with a launch line, and for every create
 * while the delegate is off.
 */
export function withDelegateSpawnSettings<T extends { initialCommand?: string; fanoutTaskOf?: string }>(
  options: T | undefined,
  deps: DelegateSpawnDeps = {},
): T | undefined {
  if (!options || !options.fanoutTaskOf || !options.initialCommand) return options;
  const dir = deps.dir ?? getWmuxDir();
  if (!(deps.isOn ?? isMoaDelegateOn)(dir)) return options;
  const settingsPath = (deps.writeProfile ?? writeWorkerDelegateProfile)(dir);
  if (!settingsPath) return options;
  const initialCommand = spliceSettingsFlag(options.initialCommand, settingsPath);
  return initialCommand === options.initialCommand ? options : { ...options, initialCommand };
}
