// ─── Moa's read gate: no prompt for reading the repos it delegated to ─────────
//
// Moa (the HQ terminal brain) checks a worker's result by reading the files it
// changed. Those files sit in another workspace's checkout, outside Moa's home,
// so every Read/Grep/Glob stopped on a permission prompt the operator had to
// answer. This gate answers the read-only ones itself, inside a narrow scope:
//
//   - WHICH TOOLS: Read, Grep and Glob only. Writes, edits and commands keep
//     their deny list or prompt.
//   - WHICH PATHS: inside a root main wrote to `moa-read-roots.json`:
//       (a) the `git rev-parse --show-toplevel` of a hand-off's pane, taken
//           once at delivery, refused when it is `/`, $HOME or an ancestor of
//           it, the wmux data dir or ~/.claude (a pane's cwd is OSC 7, i.e.
//           whatever the pane printed: unverifiable means no root);
//       (b) the worktree of an open fan-out task of the HQ (main made it).
//     Each root carries its own `expiresAt`, compared by the script itself.
//   - NEVER: a `.git` / `.ssh` / `.gnupg` / `.aws` segment, a secret file
//     (SECRET_NAMES), a hard-linked file, a symlink out of the root (paths are
//     compared after `realpathSync.native`), a directory Grep whose glob turns
//     on hidden and ignored files (measured: any glob does, no glob does not).
//   - ANYTHING ELSE, or any error: the script prints nothing and exits 0, so
//     Claude Code shows its normal prompt. It never blocks (exit 2 would turn
//     an out-of-scope read into a refusal) and never allows by default.
//
// Measured on Claude Code 2.1.289 (the PR records the runs): a PreToolUse
// `allow` skips the prompt; no output + exit 0 falls through to it; a
// settings-level `deny` still wins over a hook `allow`.

import { execFile } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { getWmuxDir } from '../../daemon/config';

/** The roots file's name in the wmux data dir. */
export const READ_ROOTS_FILE = 'moa-read-roots.json';
/** How long a root outlives its task's end while Moa still owns the job. */
export const READ_ROOT_GRACE_MS = 60 * 60_000;
/** How long an open task's root stands before main must re-stamp it. */
export const READ_ROOT_OPEN_TTL_MS = 10 * 60_000;

export interface ReadRoot {
  path: string;
  expiresAt: number;
}

export function getReadRootsPath(dir: string = getWmuxDir()): string {
  return path.join(dir, READ_ROOTS_FILE);
}

/**
 * The generated gate, run as `node read-gate.cjs <rootsFile>` for every
 * Read, Grep and Glob. Self-contained CommonJS: it runs in the brain's
 * process tree, not in main. Every path out of `main()` that is not an
 * explicit allow ends with no output and exit 0.
 */
export function buildReadGateScript(): string {
  return `// Generated by wmux (moaReadGate.ts). Regenerated on every brain spawn and
// unlinked on dispose: edits here are lost.
'use strict';
const fs = require('fs');
const path = require('path');
const WIN = process.platform === 'win32';
const SEGMENTS = new Set(['.git', '.ssh', '.gnupg', '.aws']);
const SECRET_NAMES = [
  /^\\.env(\\..*)?$/i, /\\.pem$/i, /\\.key$/i, /\\.p12$/i, /\\.pfx$/i, /\\.kdbx$/i, /\\.keystore$/i, /\\.jks$/i,
  /^id_(rsa|dsa|ecdsa|ed25519)/i, /^\\.git-credentials$/i, /^\\.pgpass$/i, /^\\.npmrc$/i, /^\\.netrc$/i, /^credentials/i,
];
// A file whose name is only secret under one folder.
const SECRET_PAIRS = [['.docker', 'config.json'], ['gh', 'hosts.yml']];
const SECRET_EXTS = new Set(['env', 'pem', 'key', 'p12', 'pfx', 'kdbx', 'keystore', 'jks', 'gpg', 'asc']);
const EXT = '[A-Za-z0-9]{1,10}';
const EXT_GLOB = new RegExp('^(?:\\\\*\\\\*/)?\\\\*\\\\.(' + EXT + '|\\\\{' + EXT + '(?:,' + EXT + ')*\\\\})$');

function norm(p) {
  if (!WIN) return p;
  let s = p;
  if (s.startsWith('\\\\\\\\?\\\\UNC\\\\')) s = '\\\\\\\\' + s.slice(8);
  else if (s.startsWith('\\\\\\\\?\\\\')) s = s.slice(4);
  return s.toLowerCase();
}
function real(p) {
  try { return norm(fs.realpathSync.native(p)); } catch { return null; }
}
function inside(target, root) {
  return target === root || target.startsWith(root.endsWith(path.sep) ? root : root + path.sep);
}
function secretPath(p) {
  const parts = p.split(/[\\\\/]+/).filter(Boolean);
  if (parts.some((s) => SEGMENTS.has(WIN ? s.toLowerCase() : s))) return true;
  const base = parts[parts.length - 1] || '';
  if (SECRET_NAMES.some((re) => re.test(base))) return true;
  const parent = (parts[parts.length - 2] || '').toLowerCase();
  return SECRET_PAIRS.some(([dir, name]) => parent === dir && base.toLowerCase() === name);
}
function narrowGlob(glob) {
  const m = EXT_GLOB.exec(glob);
  if (!m) return false;
  const exts = m[1].replace(/[{}]/g, '').split(',').map((e) => e.toLowerCase());
  return exts.every((e) => !SECRET_EXTS.has(e));
}
function loadRoots(file) {
  const raw = JSON.parse(fs.readFileSync(file, 'utf8'));
  const now = Date.now();
  const out = [];
  for (const r of (raw && Array.isArray(raw.roots) ? raw.roots : [])) {
    if (!r || typeof r.path !== 'string' || typeof r.expiresAt !== 'number' || r.expiresAt <= now) continue;
    const rp = real(r.path);
    if (rp) out.push(rp);
  }
  return out;
}
// A target inside a root, as a real path, or null.
function scoped(raw, cwd, roots) {
  if (typeof raw !== 'string' || !raw) return null;
  const abs = path.isAbsolute(raw) ? raw : (typeof cwd === 'string' ? path.resolve(cwd, raw) : null);
  if (!abs) return null;
  const rp = real(abs);
  if (!rp || secretPath(rp) || secretPath(norm(abs))) return null;
  return roots.some((root) => inside(rp, root)) ? rp : null;
}
function safeFile(rp) {
  const st = fs.statSync(rp);
  return st.isFile() && st.nlink <= 1;
}
function decide(input, roots) {
  const tool = input.tool_name;
  const t = input.tool_input || {};
  if (tool === 'Read') {
    const rp = scoped(t.file_path, null, roots);
    return !!rp && safeFile(rp);
  }
  if (tool === 'Grep') {
    const rp = scoped(t.path, input.cwd, roots);
    if (!rp) return false;
    const st = fs.statSync(rp);
    if (st.isFile()) return safeFile(rp);
    if (!st.isDirectory()) return false;
    // Measured: with a glob, the search takes hidden and ignored files too.
    if (t.glob === undefined) return true;
    return typeof t.glob === 'string' && narrowGlob(t.glob);
  }
  if (tool === 'Glob') {
    const rp = scoped(t.path, input.cwd, roots);
    if (!rp || !fs.statSync(rp).isDirectory()) return false;
    const pattern = t.pattern;
    return typeof pattern === 'string' && !!pattern && !path.isAbsolute(pattern)
      && !pattern.split(/[\\\\/]+/).includes('..') && !secretPath(pattern);
  }
  return false;
}
let input = '';
process.stdin.on('data', (d) => { input += d; });
process.stdin.on('end', () => {
  try {
    const roots = loadRoots(process.argv[2]);
    if (roots.length > 0 && decide(JSON.parse(input), roots)) {
      process.stdout.write(JSON.stringify({ hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'allow',
        permissionDecisionReason: 'A read inside a repository Moa delegated work to.',
      } }));
    }
  } catch {
    /* no decision: Claude Code shows its normal prompt */
  }
  process.exit(0);
});
`;
}

/** Write the roots atomically (temp file, then rename), owner-only. */
export function writeReadRoots(file: string, roots: readonly ReadRoot[]): void {
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(tmp, `${JSON.stringify({ version: 1, roots }, null, 2)}\n`, { encoding: 'utf8', mode: 0o600 });
  fs.renameSync(tmp, file);
}

/**
 * Is this a directory Moa may read freely? Never the filesystem root, the
 * home directory or anything above it, the wmux data dir or ~/.claude (or
 * anything inside those two). Compared as real paths.
 */
export function isAcceptableReadRoot(
  root: string,
  opts: { home?: string; blocked?: readonly string[]; realpath?: (p: string) => string } = {},
): boolean {
  const realpath = opts.realpath ?? ((p: string) => fs.realpathSync.native(p));
  let r: string;
  let home: string;
  try {
    r = realpath(root);
    home = realpath(opts.home ?? os.homedir());
  } catch {
    return false;
  }
  const inside = (a: string, b: string): boolean => a === b || a.startsWith(b.endsWith(path.sep) ? b : b + path.sep);
  if (r === path.parse(r).root) return false;
  if (inside(home, r)) return false; // $HOME itself or an ancestor of it
  for (const b of opts.blocked ?? [getWmuxDir(), path.join(os.homedir(), '.claude')]) {
    let rb: string;
    try {
      rb = realpath(b);
    } catch {
      continue;
    }
    if (inside(r, rb) || inside(rb, r)) return false;
  }
  return true;
}

/** `git rev-parse --show-toplevel` in `cwd`, accepted only when it succeeds
 *  and names an acceptable root (isAcceptableReadRoot). Null otherwise. */
export function resolveRepoRoot(
  cwd: string | undefined,
  opts: { run?: (cwd: string) => Promise<string | null>; accept?: (root: string) => boolean } = {},
): Promise<string | null> {
  if (!cwd || !path.isAbsolute(cwd)) return Promise.resolve(null);
  const run = opts.run ?? ((dir: string) => new Promise<string | null>((resolve) => {
    execFile('git', ['-C', dir, 'rev-parse', '--show-toplevel'], { timeout: 5_000, windowsHide: true }, (err, stdout) => {
      resolve(err ? null : String(stdout).trim() || null);
    });
  }));
  const accept = opts.accept ?? ((root: string) => isAcceptableReadRoot(root));
  return run(cwd).then((root) => (root && path.isAbsolute(root) && accept(root) ? root : null)).catch(() => null);
}

/** What the roots are computed from. */
export interface ReadRootSources {
  now: number;
  /** The setting is on and Moa runs. Off: no roots at all. */
  enabled: boolean;
  /** Hand-offs of the current HQ that carry a captured repo root. */
  handoffs: ReadonlyArray<{
    repoRoot?: string;
    taskId?: string;
    open: boolean;
    /** When the task ended; absent while it is open. */
    endedAt?: number;
    /** wmux ended it because its pane closed: no grace. */
    paneGone?: boolean;
  }>;
  /** Task ids the HQ's live request still tracks (its active work). */
  liveTaskIds: ReadonlySet<string>;
  /** Worktrees of the HQ's open fan-out tasks. */
  fanoutWorktrees: readonly string[];
}

/**
 * The roots to write. An open hand-off's root stands (re-stamped each
 * refresh); an ended one stays up to READ_ROOT_GRACE_MS after its end, and
 * only while Moa's live request still tracks its task: finishing the job,
 * the pane closing, or Moa going off removes it at once.
 */
export function computeReadRoots(src: ReadRootSources): ReadRoot[] {
  if (!src.enabled) return [];
  const best = new Map<string, number>();
  const add = (p: string, expiresAt: number): void => {
    if (expiresAt <= src.now) return;
    best.set(p, Math.max(best.get(p) ?? 0, expiresAt));
  };
  for (const h of src.handoffs) {
    if (!h.repoRoot) continue;
    if (h.open) add(h.repoRoot, src.now + READ_ROOT_OPEN_TTL_MS);
    else if (!h.paneGone && h.endedAt !== undefined && h.taskId && src.liveTaskIds.has(h.taskId)) {
      add(h.repoRoot, h.endedAt + READ_ROOT_GRACE_MS);
    }
  }
  for (const w of src.fanoutWorktrees) add(w, src.now + READ_ROOT_OPEN_TTL_MS);
  return [...best.entries()].map(([p, expiresAt]) => ({ path: p, expiresAt })).sort((a, b) => a.path.localeCompare(b.path));
}

let refresher: (() => Promise<void>) | null = null;
/** deck.handler installs the refresh; deck.rpc calls it after a finished job. */
export function setMoaReadRootsRefresher(fn: (() => Promise<void>) | null): void {
  refresher = fn;
}
export function refreshMoaReadRoots(): Promise<void> {
  return refresher ? refresher().catch(() => undefined) : Promise.resolve();
}
